### ISSUE TITLE
Roadmap towards Babylon.js 4.0.0 - Feature Backlog

### ISSUE THREAD

**Issue by samdauwe** [samdauwe/BabylonCpp#36]
- [x] Update to Babylon.js version v4.0.0
    - [x] Core library
    - [x] glTF loader
    - [x] Inspector
    - [x] Materials library
    - [x] Procedural textures library
- [x] Add unit tests for BabylonCpp Core library
- [x] Resolve example issues
    - [x] Animations
    - [x] Cameras
    - [x] Collisions and Intersections
    - [x] Extensions
    - [x] Lights
    - [x] Loaders
        - [x] babylon
    - [x] Materials
    - [x] Materials Library
    - [x] Meshes
    - [x] Optimizations
    - [x] Particles
    - [x] Procedural textures library 
    - [x] Shadows
    - [x] Special FX
    - [x] Textures
- [x] Full Windows support
- [x] Improve [feature support](https://doc.babylonjs.com/examples/):
    - [x] Shadows
    - [x] Special FX
- [x] Improve code quality
